POST yii2.test/rest-shop/product/create?XDEBUG_SESSION_START=1
Accept: application/json;
Cache-Control: no-cache
Content-Type: application/json;
Authorization: Bearer YmFuazpiYW5r

{
  "name": "продукт2",
  "isdeleted": 0,
  "published": 1,
  "deleted_at": null,
  "price": "12.00",
  "shopProductCategories": [
    {
      "category_id": 5
    },
    {
      "category_id": 3
    }
  ]
}

###

PUT yii2.test/rest-shop/product/update?id=1XDEBUG_SESSION_START=1
Accept: application/json;
Cache-Control: no-cache
Content-Type: application/json;

{
  "name": "продукт2_update",
  "isdeleted": 0,
  "published": 1,
  "deleted_at": null,
  "price": "12.00"
}

###
POST yii2.test/rest-shop/product/create?XDEBUG_SESSION_START=1
Accept: application/json;
Cache-Control: no-cache
Content-Type: application/json;
Authorization: Bearer YmFuazpiYW5r

{
  "": "1",
  "name": "id_1",
  "isdeleted": 0,
  "published": 1,
  "deleted_at": null,
  "price": "12.00"
}

####



DELETE yii2.test/rest-shop/product/delete?id=1&XDEBUG_SESSION_START=1
Accept: application/json;
Cache-Control: no-cache

#############


GET  yii2.test/rest-shop/product/index?page=1&per-page=10&XDEBUG_SESSION_START=1
Accept: application/json;
Cache-Control: no-cache

#############
GET  yii2.test/rest-shop/product/index?price_min=10&price_max=12.00
Accept: application/json;
Cache-Control: no-cache

#############

GET  yii2.test/rest-shop/product/index?isdeleted=1
Accept: application/json;
Cache-Control: no-cache

#############
GET  yii2.test/rest-shop/product/index?category_id=5
Accept: application/json;
Cache-Control: no-cache

#############
GET  yii2.test/rest-shop/product/index?category_name=id_01
Accept: application/json;
Cache-Control: no-cache

#############